<?php
// A simple, self-contained installer script for the Flix9 Hub project.

// --- Configuration & Security ---
error_reporting(E_ALL);
ini_set('display_errors', 1);

// If config.php already exists, it means the site is likely installed.
// For security, we block access to the installer.
if (file_exists('config.php')) {
    die("<b>Installer Locked.</b><br>The <code>config.php</code> file already exists. To re-run the installer, you must first delete it. However, be aware that re-running the installer may overwrite your existing database tables if they use the same names.");
}

$step = $_GET['step'] ?? 1;

// --- Helper Functions ---
function check_requirements() {
    $errors = [];
    if (version_compare(PHP_VERSION, '7.4', '<')) {
        $errors[] = 'PHP version 7.4 or higher is required. You are running ' . PHP_VERSION;
    }
    if (!extension_loaded('mysqli')) {
        $errors[] = 'The MySQLi extension is not enabled.';
    }
    if (!is_writable(__DIR__)) {
        $errors[] = 'The root directory is not writable. Please check file permissions.';
    }
    return $errors;
}

function execute_sql_from_file($mysqli, $filepath) {
    $sql = file_get_contents($filepath);
    if ($sql === false) {
        return false;
    }
    // Execute multi-query
    if ($mysqli->multi_query($sql)) {
        // Clear results from each query
        do {
            if ($result = $mysqli->store_result()) {
                $result->free();
            }
        } while ($mysqli->next_result());
        return true;
    }
    return false;
}

// --- Main Logic ---
$db_host = $_POST['db_host'] ?? 'localhost';
$db_name = $_POST['db_name'] ?? '';
$db_user = $_POST['db_user'] ?? '';
$db_pass = $_POST['db_pass'] ?? '';
$errors = [];

if ($step == 3 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    // --- Step 3: Process the installation ---
    if (empty($db_host) || empty($db_name) || empty($db_user)) {
        $errors[] = "Database host, name, and username are required.";
    } else {
        // 1. Connect to MySQL server
        $mysqli = @new mysqli($db_host, $db_user, $db_pass);
        if ($mysqli->connect_error) {
            $errors[] = "Database connection failed: " . $mysqli->connect_error;
        } else {
            // 2. Create the database
            if (!$mysqli->query("CREATE DATABASE IF NOT EXISTS `$db_name`")) {
                $errors[] = "Could not create database: " . $mysqli->error;
            } else {
                $mysqli->select_db($db_name);
                // 3. Execute the schema.sql file
                if (!execute_sql_from_file($mysqli, 'schema.sql')) {
                    $errors[] = "Could not execute schema.sql: " . $mysqli->error;
                } else {
                    // 4. Create the config.php file
                    $config_content = "<?php
// Auto-generated by Flix9 Hub Installer
session_start();

// --- Database Configuration ---
define('DB_HOST', '{$db_host}');
define('DB_USERNAME', '{$db_user}');
define('DB_PASSWORD', '{$db_pass}');
define('DB_NAME', '{$db_name}');

// --- Email Configuration (Placeholders) ---
define('MAIL_HOST', 'smtp.example.com');
define('MAIL_USERNAME', 'noreply@flix9hub.com');
define('MAIL_PASSWORD', 'your_smtp_password');
define('MAIL_PORT', 587);
define('MAIL_ENCRYPTION', 'tls');
define('MAIL_FROM_ADDRESS', 'noreply@flix9hub.com');
define('MAIL_FROM_NAME', 'Flix9 Hub');

// --- Site & File Path Configuration ---
define('SITE_URL', 'http://' . \$_SERVER['HTTP_HOST']);
define('UPLOADS_PATH', __DIR__ . '/uploads');
?>";
                    if (!file_put_contents('config.php', $config_content)) {
                        $errors[] = "Could not write to config.php. Please check file permissions.";
                    } else {
                        // Success! Redirect to the final step.
                        header('Location: install.php?step=4');
                        exit();
                    }
                }
            }
            $mysqli->close();
        }
    }
    // If we have errors, fall back to step 2 to show them
    $step = 2;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flix9 Hub Installation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f0f2f5; color: #333; line-height: 1.6; }
        .container { background: #fff; max-width: 700px; margin: 50px auto; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
        h1, h2 { color: #000428; }
        .btn { display: inline-block; padding: 12px 25px; background: #004e92; color: #fff; text-decoration: none; border-radius: 5px; font-weight: bold; }
        .btn:hover { background: #003a70; }
        .error, .success, .warning { padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .error { background: #ffebee; color: #c62828; border: 1px solid #c62828; }
        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .warning { background: #fff3cd; color: #856404; border: 1px solid #ffeeba; }
        ul { list-style: none; padding: 0; }
        ul li { margin-bottom: 10px; }
        .form-group { margin-bottom: 15px; }
        .form-group label { display: block; font-weight: bold; margin-bottom: 5px; }
        .form-group input { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Flix9 Hub Installation</h1>

        <?php if ($step == 1): ?>
            <h2>Step 1: Pre-installation Checks</h2>
            <?php $req_errors = check_requirements(); ?>
            <?php if (!empty($req_errors)): ?>
                <div class="error">
                    <p>The following requirements are not met:</p>
                    <ul>
                        <?php foreach ($req_errors as $err): ?>
                            <li><?php echo $err; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php else: ?>
                <div class="success">All requirements are met. You can proceed with the installation.</div>
                <p><a href="install.php?step=2" class="btn">Start Installation</a></p>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($step == 2): ?>
            <h2>Step 2: Database Configuration</h2>
            <p>Please provide your database connection details.</p>
            <?php if (!empty($errors)): ?>
                <div class="error">
                    <ul>
                        <?php foreach ($errors as $err): ?>
                            <li><?php echo $err; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <form action="install.php?step=3" method="post">
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" name="db_host" id="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" name="db_name" id="db_name" required>
                </div>
                <div class="form-group">
                    <label for="db_user">Database Username</label>
                    <input type="text" name="db_user" id="db_user" required>
                </div>
                <div class="form-group">
                    <label for="db_pass">Database Password</label>
                    <input type="password" name="db_pass" id="db_pass">
                </div>
                <button type="submit" class="btn">Install Now</button>
            </form>
        <?php endif; ?>

        <?php if ($step == 4): ?>
            <h2>Step 3: Installation Complete!</h2>
            <div class="success">
                <p>Congratulations! Flix9 Hub has been installed successfully.</p>
            </div>
            <div class="warning">
                <h3>IMPORTANT: Delete this file!</h3>
                <p>For security reasons, you must now delete the <strong>install.php</strong> file from your server.</p>
            </div>
            <p><a href="index.php" class="btn">Go to Homepage</a></p>
            <p><a href="admin/login.php" class="btn" style="background-color: #000428;">Go to Admin Login</a></p>
        <?php endif; ?>

    </div>
</body>
</html>
